language: node_js
node_js:
- 10
deploy:
  edge: true
  provider: npm
  email: cemyderin@gmail.com
  api_key:
    secure: Kiq8ZkkUzquXsEyzJBMvw2n/j0cz1DyRD0qFK1D7bsVtwZmGBASPh5AbftqcK0v6kBKl1/UxT9BZp4emHOPGYO8BY+C1XIvIvNAXrtsJkGcWGVd+GB+QnYP26RXtpWoQ8+EOmhyPVkj7i9ENEDEZ3f184YnwcvRLkYvH9I71ALwrb1+uwISDh3ZnXjD21pPmVImj8UGyjcn6KObYD/RYIPKK5Ae6j42RPS9IS963peSFp8cQ6rqhxmdG5w0DWlOvU6E7jjuzhhztmCNw3h+EMdMFD1UTLEEpAjEyC39lInFcmlckYX6dazvDImRjaOeeIWSDu9rCTeaiKh37nSEsrJcjAZUmyqGKzd/O7UY5WxVROWTqtoT1aGSZ+TJhr3J+22BAs/sP25jtfw3SbABEt8YpX8lYENX4ckaxpmnoywh92vtZuyZuubNzv3OH9yAdhym+XIon1iwmPW+dxc5Vw/+aLqWopEZuN3m4XTuxgSMdtWWMAvLkfhIzNJ8U8nib+0Zlz9Ok3fDMOIWrEoz3O0MZxxdNd39Ca4vA+DNVKh8LTy1pjBcPH3xQNo9BZxHnb1NHiV+9B2JceBzEQQE0KkcJtxRzrUJyqBIPznC6L3IrZGb+5Rer5hxKforPYPMqHsIDqSyLIyXEWuDTFTSS7d3P3EFoqMUsXznxjoa1Trg=
  on:
    repo: cemderin/battle-simulator
    branch: master
